-- stock_master: basic symbol/name mapping table
CREATE TABLE stock_master (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR2(32) NOT NULL,
    name_ko VARCHAR2(255) NOT NULL,
    name_en VARCHAR2(255) NOT NULL,
    market VARCHAR2(32) NOT NULL,
    country VARCHAR2(8) NOT NULL,
    provider VARCHAR2(32) NOT NULL,
    provider_symbol VARCHAR2(64) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_stock_master_provider_symbol UNIQUE (provider, provider_symbol)
);

CREATE INDEX ix_stock_master_symbol ON stock_master (symbol);

MERGE INTO stock_master sm
USING (
    SELECT '005930' symbol, '삼성전자' name_ko, 'Samsung Electronics' name_en, 'KRX' market, 'KR' country, 'naver' provider, '005930' provider_symbol FROM dual
    UNION ALL SELECT 'NVDA', '엔비디아', 'NVIDIA', 'US', 'US', 'kis', 'NVDA' FROM dual
    UNION ALL SELECT 'CRCL', 'CRCL', 'CRCL', 'US', 'US', 'kis', 'CRCL' FROM dual
    UNION ALL SELECT 'AAPL', '애플', 'Apple', 'US', 'US', 'kis', 'AAPL' FROM dual
    UNION ALL SELECT 'TSLA', '테슬라', 'Tesla', 'US', 'US', 'kis', 'TSLA' FROM dual
) src
ON (sm.provider = src.provider AND sm.provider_symbol = src.provider_symbol)
WHEN NOT MATCHED THEN
    INSERT (symbol, name_ko, name_en, market, country, provider, provider_symbol, is_active, updated_at)
    VALUES (src.symbol, src.name_ko, src.name_en, src.market, src.country, src.provider, src.provider_symbol, 1, CURRENT_TIMESTAMP);
